### ISSUE TITLE
Как выставить чтение номеров из файла

### ISSUE THREAD

**Issue by masscontrolx** [shllwrld/ok_checker#2]
Здравствуйте, подскажите пожалуйста, как выставить чтение номеров из файла и сделать многопоток, перепробовал разные варианты, не получается сделать

**Comment by shllwrld** [comment]
> Здравствуйте, подскажите пожалуйста, как выставить чтение номеров из файла и сделать многопоток, перепробовал разные варианты, не получается сделать

done -f option
